### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Project)
add_subdirectory(ProjectContent)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Projectplugin
    ProjectContentplugin)